OPizza/OPizza/urls.py
from django.contrib import admin
from django.urls import path, include

import debug_toolbar


urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),

    path('restaurant/', include('restaurant.urls')),
]

OPizza/restaurant/urls.py
from django.urls import path

from .views import *
from .API import *


app_name = 'restaurant'

urlpatterns = [
    # Restaurant views for site
    path('', RestaurantListView.as_view(), name='restr'),
    path('<int:pk>/', RestaurantDetailView.as_view(), name='restr-detail'),

    # API views
    path('api/v1/', RestaurantListAPIView.as_view()),
]

OPizza/restaurant/models.py
from django.db import models


class Restaurant(models.Model):
    """Restaurant model."""

    name = models.CharField(max_length=50)
    # Address
    rating = models.FloatField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'
    

class Meal(models.Model):
    """Meal model.
    Represents the meal that restaurant selling"""

    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    name = models.CharField(max_length=50)
    price = models.FloatField()

    def __str__(self):
        return f'{self.restaurant} - {self.name}'
    
    # def get_abolute_url(self):
    #     pass
    

OPizza/restaurant/views/restaurant.py
from django.views.generic import ListView, DetailView

from restaurant.models import Restaurant


class RestaurantListView(ListView):
    model = Restaurant
    context_object_name = 'restaurants'
    template_name = 'base.html'


class RestaurantDetailView(DetailView):
    model = Restaurant
    template_name = 'restaurant/detail.html'
    context_object_name = 'restaurant'

    # def get(self, request, *args, **kwargs):
    #     meals = find_meals()

OPizza/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% block css %}
        <link href="{% static 'restaurant/CSS/normalize.css' %}" rel="stylesheet">
        <link href="{% static 'restaurant/CSS/styles.css' %}", rel="stylesheet">
    {% endblock %}
    <title>OPizza! | MainPage</title>
</head>
<body>

    <header>
        {% block header %}
            <section class="section--logos">
                <a href="{% url 'restaurant:restr' %}">
                    <img class="pizza-icon" src="{% static 'restaurant/images/pizza.png' %}">
                    <span>OPizza!</span>
                </a>
            </section>
            <section class="section--search-bar">
                
            </section>
            <section class="section--additional">
                <a class="section--additional__a" href="#">About us</a>
                <a class="section--additional__a" href="#">Doc</a>
                <a class="section--additional__a" href="#">Menu</a>  
            </section>
        {% endblock %}
    </header>
    
    <main>
        {% block content %}
            <section class="section--main">
                {% for r in restaurants %}
                    <article>
                        <div class="section--main__article">
                            <div class="section--main__article__image">
                                {{ r.image }}
                            </div>
                            <div class="sections--main__article__info">
                                {{ r.name }}<br>
                                {{ r.rating }}
                            </div>
                        </div>
                    </article>
                    <hr>
                {% endfor %}
            </section>
        {% endblock %}
    </main>
        
    <footer>
        {% block footer %}
            <section class="section--footer">
                <div class="section--footer__info">
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque deserunt nesciunt distinctio laboriosam perferendis excepturi esse, ad ducimus deleniti labore tenetur vitae accusamus, illo totam saepe, recusandae consectetur. Placeat, temporibus.
                </div>
            </section>
        {% endblock %}
    </footer>
    
</body>
</html>

OPizza/templates/restaurant/detail.html
{% extends 'base.html' %}

{% block content %}
    something
{% endblock %}